/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_8 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] result_,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [1-1:0] M_adder__z;
  wire [1-1:0] M_adder__v;
  wire [1-1:0] M_adder__n;
  wire [16-1:0] M_adder__sum_;
  reg [6-1:0] M_adder__alufn;
  reg [16-1:0] M_adder__a;
  reg [16-1:0] M_adder__b;
  adder_9 adder_ (
    .alufn(M_adder__alufn),
    .a(M_adder__a),
    .b(M_adder__b),
    .z(M_adder__z),
    .v(M_adder__v),
    .n(M_adder__n),
    .sum_(M_adder__sum_)
  );
  
  wire [16-1:0] M_boolean__bool_;
  reg [6-1:0] M_boolean__alufn;
  reg [16-1:0] M_boolean__a;
  reg [16-1:0] M_boolean__b;
  boolean_10 boolean_ (
    .alufn(M_boolean__alufn),
    .a(M_boolean__a),
    .b(M_boolean__b),
    .bool_(M_boolean__bool_)
  );
  
  wire [16-1:0] M_shifter__shift_;
  reg [6-1:0] M_shifter__alufn;
  reg [16-1:0] M_shifter__a;
  reg [16-1:0] M_shifter__b;
  shifter_11 shifter_ (
    .alufn(M_shifter__alufn),
    .a(M_shifter__a),
    .b(M_shifter__b),
    .shift_(M_shifter__shift_)
  );
  
  wire [16-1:0] M_compare__cmp_;
  reg [6-1:0] M_compare__alufn;
  reg [1-1:0] M_compare__z;
  reg [1-1:0] M_compare__v;
  reg [1-1:0] M_compare__n;
  compare_12 compare_ (
    .alufn(M_compare__alufn),
    .z(M_compare__z),
    .v(M_compare__v),
    .n(M_compare__n),
    .cmp_(M_compare__cmp_)
  );
  
  always @* begin
    M_adder__a = a;
    M_adder__b = b;
    M_adder__alufn = alufn;
    M_boolean__a = a;
    M_boolean__b = b;
    M_boolean__alufn = alufn;
    M_shifter__a = a;
    M_shifter__b = b;
    M_shifter__alufn = alufn;
    M_compare__alufn = alufn;
    M_compare__z = M_adder__z;
    M_compare__v = M_adder__v;
    M_compare__n = M_adder__n;
    
    case (alufn[4+1-:2])
      2'h0: begin
        result_ = M_adder__sum_;
      end
      2'h1: begin
        result_ = M_boolean__bool_;
      end
      2'h2: begin
        result_ = M_shifter__shift_;
      end
      2'h3: begin
        result_ = M_compare__cmp_;
      end
      default: begin
        result_ = 16'h0000;
      end
    endcase
    z = M_adder__z;
    v = M_adder__v;
    n = M_adder__n;
  end
endmodule
