/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module myFSM_2 (
    input clk,
    input rst,
    input center,
    input failsum,
    input failcout,
    output reg a,
    output reg b,
    output reg ab,
    output reg cin,
    output reg ac,
    output reg bc,
    output reg abc,
    output reg blink
  );
  
  
  
  localparam IDLE_state = 4'd0;
  localparam TEST_state = 4'd1;
  localparam A_state = 4'd2;
  localparam B_state = 4'd3;
  localparam AB_state = 4'd4;
  localparam CIN_state = 4'd5;
  localparam AC_state = 4'd6;
  localparam BC_state = 4'd7;
  localparam ABC_state = 4'd8;
  localparam FAILED_state = 4'd9;
  
  reg [3:0] M_state_d, M_state_q = IDLE_state;
  
  reg [23:0] M_counter_d, M_counter_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    a = 1'h0;
    b = 1'h0;
    ab = 1'h0;
    cin = 1'h0;
    ac = 1'h0;
    bc = 1'h0;
    abc = 1'h0;
    blink = 1'h0;
    
    case (M_state_q)
      IDLE_state: begin
        M_counter_d = 1'h0;
        if (center) begin
          M_state_d = TEST_state;
        end
      end
      FAILED_state: begin
        M_counter_d = M_counter_q + 1'h1;
        blink = M_counter_q[23+0-:1];
        if (center) begin
          M_state_d = TEST_state;
        end
      end
      TEST_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = A_state;
          a = 1'h1;
          b = 1'h0;
          ab = 1'h0;
          cin = 1'h0;
          ac = 1'h0;
          bc = 1'h0;
          abc = 1'h0;
        end
      end
      A_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (failsum) begin
          M_state_d = FAILED_state;
        end
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = B_state;
          a = 1'h0;
          b = 1'h1;
          ab = 1'h0;
          cin = 1'h0;
          ac = 1'h0;
          bc = 1'h0;
          abc = 1'h0;
        end
      end
      B_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (failsum) begin
          M_state_d = FAILED_state;
        end
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = AB_state;
          a = 1'h0;
          b = 1'h0;
          ab = 1'h1;
          cin = 1'h0;
          ac = 1'h0;
          bc = 1'h0;
          abc = 1'h0;
        end
      end
      AB_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (failcout) begin
          M_state_d = FAILED_state;
        end
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = CIN_state;
          a = 1'h0;
          b = 1'h0;
          ab = 1'h0;
          cin = 1'h1;
          ac = 1'h0;
          bc = 1'h0;
          abc = 1'h0;
        end
      end
      CIN_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (failsum) begin
          M_state_d = FAILED_state;
        end
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = AC_state;
          a = 1'h0;
          b = 1'h0;
          ab = 1'h0;
          cin = 1'h0;
          ac = 1'h1;
          bc = 1'h0;
          abc = 1'h0;
        end
      end
      AC_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (failcout) begin
          M_state_d = FAILED_state;
        end
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = BC_state;
          a = 1'h0;
          b = 1'h0;
          ab = 1'h0;
          cin = 1'h0;
          ac = 1'h0;
          bc = 1'h1;
          abc = 1'h0;
        end
      end
      BC_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (failcout) begin
          M_state_d = FAILED_state;
        end
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = ABC_state;
          a = 1'h0;
          b = 1'h0;
          ab = 1'h0;
          cin = 1'h0;
          ac = 1'h0;
          bc = 1'h0;
          abc = 1'h1;
        end
      end
      ABC_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (M_counter_q[23+0-:1]) begin
          M_counter_d = 1'h0;
          M_state_d = IDLE_state;
          a = 1'h0;
          b = 1'h0;
          ab = 1'h0;
          cin = 1'h0;
          ac = 1'h0;
          bc = 1'h0;
          abc = 1'h0;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
